[2025-01-21T00:05:21.105+0000] {processor.py:186} INFO - Started process (PID=13657) to work on /opt/airflow/dags/test.py
[2025-01-21T00:05:21.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:05:21.109+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:05:21.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:05:21.151+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:05:21.166+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:05:21.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:05:21.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:05:21.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.101 seconds
[2025-01-21T00:05:51.486+0000] {processor.py:186} INFO - Started process (PID=13722) to work on /opt/airflow/dags/test.py
[2025-01-21T00:05:51.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:05:51.491+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:05:51.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:05:51.528+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:05:51.540+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:05:51.534+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:05:51.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:05:51.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.094 seconds
[2025-01-21T00:06:12.958+0000] {processor.py:186} INFO - Started process (PID=13787) to work on /opt/airflow/dags/test.py
[2025-01-21T00:06:12.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:06:12.964+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:06:12.963+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:06:13.117+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:06:13.135+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:06:13.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:06:13.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:06:13.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.215 seconds
[2025-01-21T00:06:43.583+0000] {processor.py:186} INFO - Started process (PID=13852) to work on /opt/airflow/dags/test.py
[2025-01-21T00:06:43.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:06:43.587+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:06:43.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:06:43.626+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:06:43.640+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:06:43.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:06:43.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:06:43.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.099 seconds
[2025-01-21T00:07:14.239+0000] {processor.py:186} INFO - Started process (PID=13917) to work on /opt/airflow/dags/test.py
[2025-01-21T00:07:14.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:07:14.243+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:07:14.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:07:14.268+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:07:14.278+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:07:14.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:07:14.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:07:14.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.078 seconds
[2025-01-21T00:07:45.029+0000] {processor.py:186} INFO - Started process (PID=13982) to work on /opt/airflow/dags/test.py
[2025-01-21T00:07:45.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:07:45.033+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:07:45.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:07:45.065+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:07:45.078+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:07:45.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:07:45.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:07:45.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.091 seconds
[2025-01-21T00:08:15.350+0000] {processor.py:186} INFO - Started process (PID=14047) to work on /opt/airflow/dags/test.py
[2025-01-21T00:08:15.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:08:15.354+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:08:15.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:08:15.377+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:08:15.388+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:08:15.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:08:15.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:08:15.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.077 seconds
[2025-01-21T00:08:45.797+0000] {processor.py:186} INFO - Started process (PID=14112) to work on /opt/airflow/dags/test.py
[2025-01-21T00:08:45.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:08:45.800+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:08:45.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:08:45.830+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:08:45.842+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:08:45.834+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:08:45.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:08:45.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.094 seconds
[2025-01-21T00:09:16.852+0000] {processor.py:186} INFO - Started process (PID=14177) to work on /opt/airflow/dags/test.py
[2025-01-21T00:09:16.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:09:16.862+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:09:16.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:09:16.905+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:09:16.925+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:09:16.914+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:09:16.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:09:16.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.115 seconds
[2025-01-21T00:09:47.138+0000] {processor.py:186} INFO - Started process (PID=14242) to work on /opt/airflow/dags/test.py
[2025-01-21T00:09:47.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:09:47.144+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:09:47.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:09:47.186+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:09:47.205+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:09:47.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:09:47.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:09:47.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.120 seconds
[2025-01-21T00:10:17.450+0000] {processor.py:186} INFO - Started process (PID=14307) to work on /opt/airflow/dags/test.py
[2025-01-21T00:10:17.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:10:17.466+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:10:17.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:10:17.498+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:10:17.516+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:10:17.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:10:17.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:10:17.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.121 seconds
[2025-01-21T00:10:47.797+0000] {processor.py:186} INFO - Started process (PID=14371) to work on /opt/airflow/dags/test.py
[2025-01-21T00:10:47.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:10:47.800+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:10:47.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:10:47.823+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:10:47.835+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:10:47.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:10:47.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:10:47.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.071 seconds
[2025-01-21T00:11:19.423+0000] {processor.py:186} INFO - Started process (PID=14431) to work on /opt/airflow/dags/test.py
[2025-01-21T00:11:19.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:11:19.426+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:11:19.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:11:19.452+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:11:19.459+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:11:19.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:11:19.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:11:19.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.074 seconds
[2025-01-21T00:11:50.456+0000] {processor.py:186} INFO - Started process (PID=14492) to work on /opt/airflow/dags/test.py
[2025-01-21T00:11:50.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:11:50.459+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:11:50.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:11:50.484+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:11:50.493+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:11:50.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:11:50.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:11:50.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.075 seconds
[2025-01-21T00:12:20.893+0000] {processor.py:186} INFO - Started process (PID=14552) to work on /opt/airflow/dags/test.py
[2025-01-21T00:12:20.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:12:20.896+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:12:20.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:12:20.937+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:12:20.945+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:12:20.940+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:12:20.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:12:20.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.089 seconds
[2025-01-21T00:12:51.744+0000] {processor.py:186} INFO - Started process (PID=14616) to work on /opt/airflow/dags/test.py
[2025-01-21T00:12:51.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:12:51.749+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:12:51.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:12:51.776+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:12:51.787+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:12:51.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:12:51.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:12:51.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.089 seconds
[2025-01-21T00:12:57.162+0000] {processor.py:186} INFO - Started process (PID=14637) to work on /opt/airflow/dags/test.py
[2025-01-21T00:12:57.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:12:57.175+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:12:57.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:12:57.221+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:12:57.235+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:12:57.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from all_project_2.data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'all_project_2'
[2025-01-21T00:12:57.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:12:57.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.124 seconds
[2025-01-21T00:13:27.846+0000] {processor.py:186} INFO - Started process (PID=14701) to work on /opt/airflow/dags/test.py
[2025-01-21T00:13:27.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:13:27.849+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:13:27.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:13:27.883+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:13:27.901+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:13:27.890+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from all_project_2.data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'all_project_2'
[2025-01-21T00:13:27.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:13:27.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.092 seconds
[2025-01-21T00:13:58.227+0000] {processor.py:186} INFO - Started process (PID=14766) to work on /opt/airflow/dags/test.py
[2025-01-21T00:13:58.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:13:58.231+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:13:58.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:13:58.290+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:13:58.311+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:13:58.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from all_project_2.data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'all_project_2'
[2025-01-21T00:13:58.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:13:58.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.124 seconds
[2025-01-21T00:14:29.406+0000] {processor.py:186} INFO - Started process (PID=14832) to work on /opt/airflow/dags/test.py
[2025-01-21T00:14:29.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:14:29.409+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:14:29.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:14:29.455+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:14:29.472+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:14:29.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from all_project_2.data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'all_project_2'
[2025-01-21T00:14:29.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:14:29.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.109 seconds
[2025-01-21T00:15:00.191+0000] {processor.py:186} INFO - Started process (PID=14897) to work on /opt/airflow/dags/test.py
[2025-01-21T00:15:00.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:15:00.196+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:15:00.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:15:00.227+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:15:00.239+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:15:00.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from all_project_2.data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'all_project_2'
[2025-01-21T00:15:00.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:15:00.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.086 seconds
[2025-01-21T00:15:30.867+0000] {processor.py:186} INFO - Started process (PID=14962) to work on /opt/airflow/dags/test.py
[2025-01-21T00:15:30.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:15:30.871+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:15:30.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:15:30.902+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project\\all_project_2']
[2025-01-21T00:15:30.916+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:15:30.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from all_project_2.data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'all_project_2'
[2025-01-21T00:15:30.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:15:30.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.096 seconds
[2025-01-21T00:15:50.281+0000] {processor.py:186} INFO - Started process (PID=14970) to work on /opt/airflow/dags/test.py
[2025-01-21T00:15:50.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:15:50.285+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:15:50.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:15:50.335+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/all_project_2']
[2025-01-21T00:15:50.347+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:15:50.340+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:15:50.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:15:50.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.101 seconds
[2025-01-21T00:16:18.817+0000] {processor.py:186} INFO - Started process (PID=15035) to work on /opt/airflow/dags/test.py
[2025-01-21T00:16:18.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:16:18.821+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:16:18.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:16:18.893+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project/all_project_2']
[2025-01-21T00:16:18.916+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:16:18.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:16:18.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:16:18.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.154 seconds
[2025-01-21T00:16:35.506+0000] {processor.py:186} INFO - Started process (PID=15093) to work on /opt/airflow/dags/test.py
[2025-01-21T00:16:35.508+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:16:35.511+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:16:35.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:16:35.567+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/dags/D:\\DE_project/all_project_2']
[2025-01-21T00:16:35.584+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:16:35.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:16:35.588+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/test.py:14 SyntaxWarning: invalid escape sequence '\D'
[2025-01-21T00:16:35.589+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:16:35.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.127 seconds
[2025-01-21T00:16:58.931+0000] {processor.py:186} INFO - Started process (PID=15142) to work on /opt/airflow/dags/test.py
[2025-01-21T00:16:58.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:16:58.935+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:16:58.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:16:58.966+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/all_project_2']
[2025-01-21T00:16:58.975+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:16:58.970+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:16:58.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:16:58.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.074 seconds
[2025-01-21T00:17:29.200+0000] {processor.py:186} INFO - Started process (PID=15204) to work on /opt/airflow/dags/test.py
[2025-01-21T00:17:29.202+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:17:29.204+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:17:29.203+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:17:29.233+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/all_project_2']
[2025-01-21T00:17:29.243+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:17:29.237+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:17:29.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:17:29.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.094 seconds
[2025-01-21T00:17:59.393+0000] {processor.py:186} INFO - Started process (PID=15259) to work on /opt/airflow/dags/test.py
[2025-01-21T00:17:59.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:17:59.398+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:17:59.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:17:59.440+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/all_project_2']
[2025-01-21T00:17:59.458+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:17:59.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:17:59.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:17:59.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.108 seconds
[2025-01-21T00:18:30.027+0000] {processor.py:186} INFO - Started process (PID=15321) to work on /opt/airflow/dags/test.py
[2025-01-21T00:18:30.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:18:30.030+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:18:30.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:18:30.057+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/all_project_2']
[2025-01-21T00:18:30.069+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:18:30.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:18:30.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:18:30.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.081 seconds
[2025-01-21T00:19:00.668+0000] {processor.py:186} INFO - Started process (PID=15383) to work on /opt/airflow/dags/test.py
[2025-01-21T00:19:00.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:19:00.671+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:19:00.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:19:00.697+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/airflow/all_project_2']
[2025-01-21T00:19:00.709+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:19:00.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:19:00.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:19:00.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.103 seconds
[2025-01-21T00:19:10.391+0000] {processor.py:186} INFO - Started process (PID=15421) to work on /opt/airflow/dags/test.py
[2025-01-21T00:19:10.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:19:10.395+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:19:10.394+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:19:10.443+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:19:10.471+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:19:10.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:19:10.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:19:10.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.134 seconds
[2025-01-21T00:19:22.403+0000] {processor.py:186} INFO - Started process (PID=15428) to work on /opt/airflow/dags/test.py
[2025-01-21T00:19:22.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:19:22.406+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:19:22.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:19:22.446+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:19:22.457+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:19:22.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:19:22.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:19:22.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.093 seconds
[2025-01-21T00:19:38.088+0000] {processor.py:186} INFO - Started process (PID=15485) to work on /opt/airflow/dags/test.py
[2025-01-21T00:19:38.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:19:38.096+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:19:38.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:19:38.159+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/D:\\DE_project\\all_project_2']
[2025-01-21T00:19:38.171+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:19:38.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:19:38.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:19:38.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.136 seconds
[2025-01-21T00:20:08.380+0000] {processor.py:186} INFO - Started process (PID=15550) to work on /opt/airflow/dags/test.py
[2025-01-21T00:20:08.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:20:08.385+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:20:08.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:20:08.428+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/D:\\DE_project\\all_project_2']
[2025-01-21T00:20:08.440+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:20:08.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:20:08.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:20:08.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.104 seconds
[2025-01-21T00:20:39.629+0000] {processor.py:186} INFO - Started process (PID=15608) to work on /opt/airflow/dags/test.py
[2025-01-21T00:20:39.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:20:39.635+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:20:39.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:20:39.662+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/D:\\DE_project\\all_project_2']
[2025-01-21T00:20:39.669+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:20:39.665+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:20:39.671+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:20:39.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.083 seconds
[2025-01-21T00:21:10.762+0000] {processor.py:186} INFO - Started process (PID=15669) to work on /opt/airflow/dags/test.py
[2025-01-21T00:21:10.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:21:10.766+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:21:10.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:21:10.792+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/D:\\DE_project\\all_project_2']
[2025-01-21T00:21:10.803+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:21:10.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 25, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:21:10.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:21:10.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.085 seconds
[2025-01-21T00:21:25.231+0000] {processor.py:186} INFO - Started process (PID=15689) to work on /opt/airflow/dags/test.py
[2025-01-21T00:21:25.233+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:21:25.236+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:21:25.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:21:25.331+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:21:25.355+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:21:25.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:21:25.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:21:25.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.176 seconds
[2025-01-21T00:21:42.801+0000] {processor.py:186} INFO - Started process (PID=15732) to work on /opt/airflow/dags/test.py
[2025-01-21T00:21:42.803+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:21:42.805+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:21:42.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:21:42.859+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:21:42.873+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:21:42.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:21:42.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:21:42.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.126 seconds
[2025-01-21T00:22:13.164+0000] {processor.py:186} INFO - Started process (PID=15795) to work on /opt/airflow/dags/test.py
[2025-01-21T00:22:13.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:22:13.168+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:22:13.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:22:13.195+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:22:13.203+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:22:13.199+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:22:13.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:22:13.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.077 seconds
[2025-01-21T00:22:43.996+0000] {processor.py:186} INFO - Started process (PID=15858) to work on /opt/airflow/dags/test.py
[2025-01-21T00:22:43.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:22:43.999+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:22:43.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:22:44.017+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:22:44.027+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:22:44.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:22:44.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:22:44.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.065 seconds
[2025-01-21T00:23:11.042+0000] {processor.py:186} INFO - Started process (PID=15905) to work on /opt/airflow/dags/test.py
[2025-01-21T00:23:11.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:23:11.046+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:23:11.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:23:11.117+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:23:11.135+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:23:11.125+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:23:11.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:23:11.174+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.141 seconds
[2025-01-21T00:23:14.762+0000] {processor.py:186} INFO - Started process (PID=15912) to work on /opt/airflow/dags/test.py
[2025-01-21T00:23:14.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:23:14.767+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:23:14.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:23:14.813+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:23:14.826+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:23:14.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:23:14.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:23:14.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.111 seconds
[2025-01-21T00:23:46.219+0000] {processor.py:186} INFO - Started process (PID=15976) to work on /opt/airflow/dags/test.py
[2025-01-21T00:23:46.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:23:46.222+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:23:46.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:23:46.245+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:23:46.254+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:23:46.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:23:46.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:23:46.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.074 seconds
[2025-01-21T00:24:16.534+0000] {processor.py:186} INFO - Started process (PID=16037) to work on /opt/airflow/dags/test.py
[2025-01-21T00:24:16.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:24:16.538+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:24:16.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:24:16.570+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:24:16.578+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:24:16.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:24:16.580+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:24:16.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.078 seconds
[2025-01-21T00:24:46.946+0000] {processor.py:186} INFO - Started process (PID=16101) to work on /opt/airflow/dags/test.py
[2025-01-21T00:24:46.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:24:46.949+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:24:46.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:24:46.971+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:24:46.982+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:24:46.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:24:46.984+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:24:47.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.078 seconds
[2025-01-21T00:25:17.258+0000] {processor.py:186} INFO - Started process (PID=16166) to work on /opt/airflow/dags/test.py
[2025-01-21T00:25:17.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:25:17.263+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:25:17.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:25:17.313+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:25:17.334+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:25:17.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 24, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:25:17.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:25:17.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.122 seconds
[2025-01-21T00:25:36.415+0000] {processor.py:186} INFO - Started process (PID=16231) to work on /opt/airflow/dags/test.py
[2025-01-21T00:25:36.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:25:36.419+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:25:36.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:25:36.481+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:25:36.498+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:25:36.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:25:36.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:25:36.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-01-21T00:26:06.651+0000] {processor.py:186} INFO - Started process (PID=16296) to work on /opt/airflow/dags/test.py
[2025-01-21T00:26:06.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:26:06.656+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:26:06.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:26:06.696+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:26:06.708+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:26:06.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:26:06.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:26:06.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.107 seconds
[2025-01-21T00:26:36.859+0000] {processor.py:186} INFO - Started process (PID=16360) to work on /opt/airflow/dags/test.py
[2025-01-21T00:26:36.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:26:36.863+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:26:36.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:26:36.899+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:26:36.914+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:26:36.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:26:36.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:26:36.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.121 seconds
[2025-01-21T00:27:07.386+0000] {processor.py:186} INFO - Started process (PID=16423) to work on /opt/airflow/dags/test.py
[2025-01-21T00:27:07.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:27:07.390+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:27:07.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:27:07.432+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:27:07.453+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:27:07.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:27:07.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:27:07.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.113 seconds
[2025-01-21T00:27:37.694+0000] {processor.py:186} INFO - Started process (PID=16488) to work on /opt/airflow/dags/test.py
[2025-01-21T00:27:37.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:27:37.698+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:27:37.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:27:37.724+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:27:37.734+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:27:37.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:27:37.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:27:37.766+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.080 seconds
[2025-01-21T00:28:08.607+0000] {processor.py:186} INFO - Started process (PID=16552) to work on /opt/airflow/dags/test.py
[2025-01-21T00:28:08.609+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:28:08.612+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:28:08.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:28:08.651+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:28:08.661+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:28:08.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:28:08.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:28:08.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.100 seconds
[2025-01-21T00:28:39.360+0000] {processor.py:186} INFO - Started process (PID=16617) to work on /opt/airflow/dags/test.py
[2025-01-21T00:28:39.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:28:39.365+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:28:39.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:28:39.391+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:28:39.403+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:28:39.398+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:28:39.405+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:28:39.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.091 seconds
[2025-01-21T00:29:10.158+0000] {processor.py:186} INFO - Started process (PID=16682) to work on /opt/airflow/dags/test.py
[2025-01-21T00:29:10.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:29:10.162+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:29:10.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:29:10.195+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:29:10.207+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:29:10.198+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:29:10.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:29:10.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.095 seconds
[2025-01-21T00:29:40.647+0000] {processor.py:186} INFO - Started process (PID=16747) to work on /opt/airflow/dags/test.py
[2025-01-21T00:29:40.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:29:40.651+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:29:40.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:29:40.693+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:29:40.703+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:29:40.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:29:40.707+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:29:40.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.105 seconds
[2025-01-21T00:30:11.012+0000] {processor.py:186} INFO - Started process (PID=16812) to work on /opt/airflow/dags/test.py
[2025-01-21T00:30:11.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:30:11.015+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:30:11.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:30:11.040+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:30:11.051+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:30:11.045+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:30:11.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:30:11.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.076 seconds
[2025-01-21T00:30:41.736+0000] {processor.py:186} INFO - Started process (PID=16874) to work on /opt/airflow/dags/test.py
[2025-01-21T00:30:41.738+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:30:41.740+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:30:41.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:30:41.778+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:30:41.791+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:30:41.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:30:41.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:30:41.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.094 seconds
[2025-01-21T00:31:12.560+0000] {processor.py:186} INFO - Started process (PID=16939) to work on /opt/airflow/dags/test.py
[2025-01-21T00:31:12.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:31:12.563+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:31:12.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:31:12.592+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:31:12.606+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:31:12.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:31:12.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:31:12.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.083 seconds
[2025-01-21T00:31:43.591+0000] {processor.py:186} INFO - Started process (PID=16996) to work on /opt/airflow/dags/test.py
[2025-01-21T00:31:43.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:31:43.596+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:31:43.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:31:43.628+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:31:43.640+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:31:43.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:31:43.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:31:43.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.088 seconds
[2025-01-21T00:32:14.045+0000] {processor.py:186} INFO - Started process (PID=17056) to work on /opt/airflow/dags/test.py
[2025-01-21T00:32:14.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:32:14.048+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:32:14.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:32:14.068+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:32:14.076+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:32:14.071+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:32:14.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:32:14.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.069 seconds
[2025-01-21T00:32:45.919+0000] {processor.py:186} INFO - Started process (PID=17112) to work on /opt/airflow/dags/test.py
[2025-01-21T00:32:45.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:32:45.922+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:32:45.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:32:45.946+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:32:45.958+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:32:45.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:32:45.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:32:46.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.095 seconds
[2025-01-21T00:33:17.098+0000] {processor.py:186} INFO - Started process (PID=17175) to work on /opt/airflow/dags/test.py
[2025-01-21T00:33:17.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T00:33:17.102+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:33:17.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T00:33:17.138+0000] {logging_mixin.py:190} INFO - Updated sys.path: ['/home/airflow/.local/bin', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/home/airflow/.local/lib/python3.12/site-packages', '/opt/airflow/config', '/opt/airflow/plugins', '/opt/airflow/dags', '/opt/all_project_2']
[2025-01-21T00:33:17.150+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:33:17.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 23, in <module>
    from data_crawl import get_brands, crawl_all_products
ModuleNotFoundError: No module named 'data_crawl'
[2025-01-21T00:33:17.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-01-21T00:33:17.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.121 seconds
